# Generated by Django 4.1.13 on 2024-03-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='shares',
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(),
        ),
    ]
