# Generated by Django 4.1.13 on 2024-04-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_post_comments_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
